version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - myapp:prod
    container_name: myapp_prod
    ports:
      - "3000:3000"
    volumes: []
    env_file:
      - .env.prod
    restart: always

  db:
    container_name: myapp_db_prod
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
