services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - myapp:dev
    container_name: myapp_dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
    command: yarn dev
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    container_name: myapp_db_dev
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  app_node_modules:
  db_data:
