version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    restart: always

    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: